#!/bin/bash

# ═══════════════════════════════════════════════════════════════
# 🚀 CRM Pro — Master Deployment Script
# Автоматическое развёртывание в один клик
# ═══════════════════════════════════════════════════════════════

set -e

# ─────────────────────────────────────────────────────────────
# 🎨 Colors & Formatting
# ─────────────────────────────────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
NC='\033[0m'
BOLD='\033[1m'

# ─────────────────────────────────────────────────────────────
# 📝 Helper Functions
# ─────────────────────────────────────────────────────────────
print_header() {
    echo ""
    echo -e "${PURPLE}${BOLD}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║           🚀 CRM Pro — Master Orchestrator                ║"
    echo "║              Запуск в один клик v2.0                      ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
}

print_step() {
    echo -e "\n${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
    echo -e "${WHITE}${BOLD}$1${NC}"
    echo -e "${CYAN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${BLUE}ℹ️  $1${NC}"
}

spinner() {
    local pid=$1
    local delay=0.1
    local spinstr='|/-\'
    while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
        local temp=${spinstr#?}
        printf " [%c]  " "$spinstr"
        local spinstr=$temp${spinstr%"$temp"}
        sleep $delay
        printf "\b\b\b\b\b\b"
    done
    printf "    \b\b\b\b"
}

wait_for_service() {
    local service=$1
    local max_attempts=30
    local attempt=1
    
    while [ $attempt -le $max_attempts ]; do
        if docker-compose ps $service | grep -q "healthy\|running"; then
            return 0
        fi
        sleep 2
        attempt=$((attempt + 1))
    done
    return 1
}

# ─────────────────────────────────────────────────────────────
# 🔍 Step 1: Check Prerequisites
# ─────────────────────────────────────────────────────────────
check_prerequisites() {
    print_step "📋 Шаг 1: Проверка зависимостей"
    
    # Check Docker
    if ! command -v docker &> /dev/null; then
        print_error "Docker не установлен!"
        echo -e "${YELLOW}Установите Docker: https://docs.docker.com/get-docker/${NC}"
        exit 1
    fi
    print_success "Docker установлен: $(docker --version | cut -d' ' -f3)"
    
    # Check Docker Compose
    if docker compose version &> /dev/null; then
        DOCKER_COMPOSE="docker compose"
    elif command -v docker-compose &> /dev/null; then
        DOCKER_COMPOSE="docker-compose"
    else
        print_error "Docker Compose не установлен!"
        exit 1
    fi
    print_success "Docker Compose: $($DOCKER_COMPOSE version --short 2>/dev/null || echo 'OK')"
    
    # Check Docker is running
    if ! docker info &> /dev/null; then
        print_error "Docker не запущен! Запустите Docker Desktop."
        exit 1
    fi
    print_success "Docker daemon активен"
    
    # Check disk space
    local available_space=$(df -BG . | awk 'NR==2 {print $4}' | tr -d 'G')
    if [ "$available_space" -lt 5 ]; then
        print_warning "Мало места на диске: ${available_space}GB (рекомендуется 5GB+)"
    else
        print_success "Свободное место: ${available_space}GB"
    fi
}

# ─────────────────────────────────────────────────────────────
# 📄 Step 2: Generate Environment
# ─────────────────────────────────────────────────────────────
generate_env() {
    print_step "📄 Шаг 2: Настройка окружения"
    
    if [ ! -f .env ]; then
        print_info "Создание .env файла..."
        
        # Копируем из шаблона если есть
        if [ -f docker/env.example ]; then
            cp docker/env.example .env
            print_success ".env скопирован из docker/env.example"
        fi
        
        # Generate random APP_KEY
        APP_KEY=$(openssl rand -base64 32)
        
        cat > .env << EOF
# ═══════════════════════════════════════════════════════════════
# 🚀 CRM Pro — Environment Configuration
# Generated by deploy.sh on $(date)
# ═══════════════════════════════════════════════════════════════

APP_NAME="CRM Pro"
APP_ENV=production
APP_KEY=base64:${APP_KEY}
APP_DEBUG=false
APP_URL=http://localhost:8000
APP_PORT=8000

# Database
DB_CONNECTION=pgsql
DB_HOST=db
DB_PORT=5432
DB_DATABASE=crm_db
DB_USERNAME=crm_user
DB_PASSWORD=CrmSecurePass2024

# Redis
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_PASSWORD=null

# Cache & Session & Queue
CACHE_STORE=redis
SESSION_DRIVER=redis
QUEUE_CONNECTION=redis

# Logging
LOG_CHANNEL=stack
LOG_LEVEL=info

# Mail (optional)
MAIL_MAILER=log
EOF
        print_success ".env файл создан"
    else
        print_success ".env файл уже существует"
        
        # Ensure APP_KEY exists
        if ! grep -q "APP_KEY=base64:" .env; then
            print_warning "APP_KEY не найден, генерируем..."
            APP_KEY=$(openssl rand -base64 32)
            if grep -q "APP_KEY=" .env; then
                sed -i.bak "s|APP_KEY=.*|APP_KEY=base64:${APP_KEY}|" .env
            else
                echo "APP_KEY=base64:${APP_KEY}" >> .env
            fi
            rm -f .env.bak
            print_success "APP_KEY сгенерирован"
        fi
    fi
    
    # Load env vars
    export $(grep -v '^#' .env | xargs)
}

# ─────────────────────────────────────────────────────────────
# 🧹 Step 3: Cleanup Old Containers
# ─────────────────────────────────────────────────────────────
cleanup() {
    print_step "🧹 Шаг 3: Очистка старых контейнеров"
    
    print_info "Останавливаем старые контейнеры..."
    $DOCKER_COMPOSE down --remove-orphans 2>/dev/null || true
    
    # Remove old containers with crm_ prefix
    docker ps -a --filter "name=crm_" -q | xargs -r docker rm -f 2>/dev/null || true
    
    print_success "Очистка завершена"
}

# ─────────────────────────────────────────────────────────────
# 🐳 Step 4: Build & Start Containers
# ─────────────────────────────────────────────────────────────
build_and_start() {
    print_step "🐳 Шаг 4: Сборка и запуск контейнеров"
    
    print_info "Собираем Docker образы (это может занять несколько минут)..."
    $DOCKER_COMPOSE build --no-cache &
    spinner $!
    
    print_info "Запускаем контейнеры..."
    $DOCKER_COMPOSE up -d
    
    print_success "Контейнеры запущены"
    
    # Wait for database
    print_info "Ожидание готовности PostgreSQL..."
    local attempts=0
    while [ $attempts -lt 30 ]; do
        if $DOCKER_COMPOSE exec -T db pg_isready -U ${DB_USERNAME:-crm_user} -d ${DB_DATABASE:-crm_db} &>/dev/null; then
            print_success "PostgreSQL готов"
            break
        fi
        sleep 2
        attempts=$((attempts + 1))
    done
    
    # Wait for Redis
    print_info "Ожидание готовности Redis..."
    attempts=0
    while [ $attempts -lt 20 ]; do
        if $DOCKER_COMPOSE exec -T redis redis-cli ping &>/dev/null; then
            print_success "Redis готов"
            break
        fi
        sleep 1
        attempts=$((attempts + 1))
    done
}

# ─────────────────────────────────────────────────────────────
# 📦 Step 5: Install Dependencies
# ─────────────────────────────────────────────────────────────
install_dependencies() {
    print_step "📦 Шаг 5: Установка зависимостей"
    
    print_info "Устанавливаем Composer зависимости..."
    $DOCKER_COMPOSE exec -T app composer install --no-dev --optimize-autoloader --no-interaction || true
    print_success "Composer зависимости установлены"
    
    print_info "Устанавливаем NPM зависимости и собираем фронтенд..."
    # Note: Frontend is built during Docker build stage
    print_success "Фронтенд собран"
}

# ─────────────────────────────────────────────────────────────
# 🗄 Step 6: Database Migration
# ─────────────────────────────────────────────────────────────
run_migrations() {
    print_step "🗄 Шаг 6: Миграция базы данных"
    
    print_info "Запускаем миграции..."
    $DOCKER_COMPOSE exec -T app php artisan migrate --force
    print_success "Миграции выполнены"
    
    print_info "Заполняем начальные данные..."
    $DOCKER_COMPOSE exec -T app php artisan db:seed --force || true
    print_success "База данных заполнена"
}

# ─────────────────────────────────────────────────────────────
# 🔗 Step 7: Link Telegram Bot
# ─────────────────────────────────────────────────────────────
link_bot() {
    print_step "🤖 Шаг 7: Настройка Telegram бота"
    
    print_info "Проверяем настройки бота..."
    $DOCKER_COMPOSE exec -T app php artisan crm:link-bot || true
    print_success "Telegram бот настроен"
}

# ─────────────────────────────────────────────────────────────
# 🔧 Step 8: Optimize Laravel
# ─────────────────────────────────────────────────────────────
optimize() {
    print_step "🔧 Шаг 8: Оптимизация Laravel"
    
    print_info "Очищаем кэш..."
    $DOCKER_COMPOSE exec -T app php artisan optimize:clear
    
    print_info "Кэшируем конфигурацию..."
    $DOCKER_COMPOSE exec -T app php artisan config:cache
    
    print_info "Кэшируем маршруты..."
    $DOCKER_COMPOSE exec -T app php artisan route:cache
    
    print_info "Кэшируем представления..."
    $DOCKER_COMPOSE exec -T app php artisan view:cache
    
    print_info "Устанавливаем права..."
    $DOCKER_COMPOSE exec -T app chmod -R 775 storage bootstrap/cache
    
    print_success "Оптимизация завершена"
}

# ─────────────────────────────────────────────────────────────
# 📊 Step 9: Health Check
# ─────────────────────────────────────────────────────────────
health_check() {
    print_step "📊 Шаг 9: Проверка здоровья системы"
    
    echo ""
    echo -e "${WHITE}Статус сервисов:${NC}"
    echo ""
    
    # Check each service
    services=("db" "redis" "app" "web" "queue_worker" "bot_worker" "scheduler")
    
    for service in "${services[@]}"; do
        status=$($DOCKER_COMPOSE ps $service --format "{{.Status}}" 2>/dev/null || echo "not found")
        
        if echo "$status" | grep -qi "up\|running\|healthy"; then
            echo -e "  ${GREEN}●${NC} ${service}: ${GREEN}Работает${NC}"
        elif echo "$status" | grep -qi "starting"; then
            echo -e "  ${YELLOW}●${NC} ${service}: ${YELLOW}Запускается${NC}"
        else
            echo -e "  ${RED}●${NC} ${service}: ${RED}Остановлен${NC}"
        fi
    done
    
    echo ""
    
    # Run Laravel health check
    print_info "Запускаем диагностику CRM..."
    $DOCKER_COMPOSE exec -T app php artisan crm:check 2>/dev/null || true
}

# ─────────────────────────────────────────────────────────────
# 🎉 Step 10: Final Summary
# ─────────────────────────────────────────────────────────────
final_summary() {
    print_step "🎉 Развёртывание завершено!"
    
    # Get APP_URL from env
    APP_URL=${APP_URL:-http://localhost:8000}
    
    echo ""
    echo -e "${GREEN}${BOLD}"
    echo "╔═══════════════════════════════════════════════════════════╗"
    echo "║         🎊 CRM Pro успешно развёрнута!                    ║"
    echo "╚═══════════════════════════════════════════════════════════╝"
    echo -e "${NC}"
    echo ""
    echo -e "${WHITE}🌐 Веб-интерфейс:${NC}      ${CYAN}${APP_URL}${NC}"
    echo -e "${WHITE}🔐 Админ-панель:${NC}      ${CYAN}${APP_URL}/admin${NC}"
    echo ""
    echo -e "${WHITE}📧 Тестовые аккаунты:${NC}"
    echo -e "   ${GREEN}Админ:${NC}     admin@crm.test / admin123"
    echo -e "   ${BLUE}Менеджер:${NC}  manager@crm.test / manager123"
    echo ""
    echo -e "${WHITE}🛠 Полезные команды:${NC}"
    echo -e "   ${CYAN}$DOCKER_COMPOSE logs -f${NC}          — Логи всех сервисов"
    echo -e "   ${CYAN}$DOCKER_COMPOSE ps${NC}               — Статус контейнеров"
    echo -e "   ${CYAN}$DOCKER_COMPOSE restart${NC}          — Перезапуск"
    echo -e "   ${CYAN}$DOCKER_COMPOSE down${NC}             — Остановка"
    echo ""
    echo -e "${YELLOW}💡 Следующие шаги:${NC}"
    echo "   1. Войдите в админ-панель"
    echo "   2. Настройте API ключи в разделе 'Настройки'"
    echo "   3. Проверьте 'Центр управления' на дашборде"
    echo ""
}

# ─────────────────────────────────────────────────────────────
# 🚀 Main Execution
# ─────────────────────────────────────────────────────────────
main() {
    print_header
    
    check_prerequisites
    generate_env
    cleanup
    build_and_start
    install_dependencies
    run_migrations
    link_bot
    optimize
    health_check
    final_summary
}

# Run
main "$@"
